name: optime
description: "Application for students"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.1.2
  percent_indicator: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/googleicon.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/optime.png"
